pluralkit: 
  token: 
  systemID: 
  zeropoint: "2000-01-01T00:00:00Z"
  defaultFronter: 
  updateInterval: 5

discord:
  pingUserID: 
  full:
    enabled: true
    token: 
    serverID: 
  filtered:
    enabled: true
    token: 
    serverID: 

data: "~/.pktools"