version: "20240912"

updateInterval: 1
timeout: 120 # time in minutes

data: "/home/serve/.whome"

pluralkit: 
  token: 
  systemID: 
  zeropoint: "2000-01-01T00:00:00Z"

discord:
  pingUserID: 
  full:
    enabled: false
    token: 
    serverID: 
  filtered:
    enabled: false
    token: 
    serverID: 

mqtt:
  enabled: false
  server: 127.0.0.1
  port: 1883
  user: 
  pass: 

group:
# group: [pkgroupids]

covers:
# group id: member id
  default: 
